name: Build WA Venues CSV

on:
  schedule:
    - cron: '20 7 * * *'   # daily at ~07:20 UTC (12:20am Pacific)
  workflow_dispatch:        # lets you run it on-demand from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # needed so action can push commits
    env:
      TM_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build CSVs
        run: |
          node -v
          mkdir -p scripts data
          # (script content unchanged — generates data/combined_wa.csv, tm_wa.csv, wd_wa.csv)
          cat > scripts/build_wa_csvs.js <<'EOF'
          ... your full Node script from above ...
          EOF

          node scripts/build_wa_csvs.js

      - name: Commit CSVs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update WA venues CSV"
          file_pattern: data/*.csv
          branch: main   # ensure it pushes back to main

